server:
  port: 8081

# 普通的key - value
name: lihe

# 对象
student：
  name：lihe
  age： 3

# 行内写法
student: {name: lihe, age: 3}

# 数组

pets:
  - cat
  - dog

pets2: [cat, dog]

# properties只能保存键值对
# 对空格的要求十分高

# 可以注入到我们的配置里